// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'enabled': string;
  'implementation': string;
  'minimumSeeders': string;
  'name': string;
  'packSeedTime': string;
  'priority': string;
  'seedRatio': string;
  'seedTime': string;
  'tags': string;
}
export const cssExports: CssExports;
export default cssExports;
